name: test

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: See
      run: |
        echo "${{ github.actor	}}"
          
