name: test local

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test local action
      uses: ./test-action
      with:
        name: test
        age: ${{secrets.TEST_SECRET}}
          
